### ISSUE TITLE
Recipe View

### ISSUE THREAD

**Issue by bezi** [TheOscars2/FoodApp#18]
- [x] Fix up the item padding to have interior padding.
- [x] Drop the source for now.
- [x] No vertical padding between items, instead add a border to the items.
- [x] If there are 0 hours, don't show it.
- [x] Put a clock icon next to the time.
- [x] Make foreground color different than the background color.

**Comment by ivg2** [comment]
![screenshot_1532110641](https://user-images.githubusercontent.com/32111461/43018648-24d9f126-8c0f-11e8-8c1e-b616737e2a0e.png)

**Comment by gtihtina** [comment]
![screenshot_1532459819](https://user-images.githubusercontent.com/33697144/43160954-797c5a64-8f3b-11e8-9cab-844ad44dccc7.png)
LOOKS EVEN BETTER
