### ISSUE TITLE
Recipe Detail View

### ISSUE THREAD

**Issue by bezi** [TheOscars2/FoodApp#19]
- [x] Title overlaid over text
- [x] No picture upload unless on edit.
- [x] Edit dropdown on same level as title.
- [x] Abbreviate time as 1h2m, add clock icon.
- [x] Padding of the screen
- [x] Bulleted lists
- [x] Better default recipes
- [x] Bold the titles more
- [x] Bottom bar should be dark-on-white

**Comment by ivg2** [comment]
![ocpwbyxcig](https://user-images.githubusercontent.com/32111461/43168848-8f8ebb72-8f53-11e8-9d79-6c923287e2a7.gif)
