### ISSUE TITLE
Research Barcode Input

### ISSUE THREAD

**Issue by bezi** [TheOscars2/FoodApp#2]
This is our biggest unknown: let's nail down what will be required, etc.

Update this issue with findings.

**Comment by Gina-Valderrama** [comment]
Solution to barcode input: Google Mobile Vision library
[https://developers.google.com/vision/android/barcodes-overview](url) [https://developers.google.com/vision/android/multi-tracker-tutorial#creating_separate_graphics_for_barcodes_and_faces](url)
   
We'll build a back end to translate the barcode number into an actual product object
