### ISSUE TITLE
Recipe Creation View

### ISSUE THREAD

**Issue by bezi** [TheOscars2/FoodApp#20]
- [x] Add basic copy.
- [ ] Error validation without crashing
- [x] Next button next to the 'Add' 
- [x] Put bullets
- [x] Long text input on instructions
- [x] Better placeholder image.

**Comment by ivg2** [comment]
![screenshot_1532111308](https://user-images.githubusercontent.com/32111461/43019126-bce46de2-8c10-11e8-9e88-66be67681d6b.png)
![screenshot_1532111365](https://user-images.githubusercontent.com/32111461/43019127-bcfdb306-8c10-11e8-8038-f46f95b1e3d6.png)
![screenshot_1532111383](https://user-images.githubusercontent.com/32111461/43019128-bd12bd32-8c10-11e8-97ed-38e6efaae362.png)
![screenshot_1532111457](https://user-images.githubusercontent.com/32111461/43019129-bd2780b4-8c10-11e8-9a4a-4401083afdb3.png)
![screenshot_1532111445](https://user-images.githubusercontent.com/32111461/43019131-bd423238-8c10-11e8-83b1-2e057e160ff6.png)
