### ISSUE TITLE
Fridge View

### ISSUE THREAD

**Issue by bezi** [TheOscars2/FoodApp#22]
- [ ] Background color change
- [x] Add small padding to distinguish icons
- [x] Center the text

**Comment by ivg2** [comment]
![screenshot_1532112457](https://user-images.githubusercontent.com/32111461/43019853-18f7525a-8c13-11e8-901e-bc7cdd7403a5.png)

**Comment by gtihtina** [comment]
![screenshot_1532459629](https://user-images.githubusercontent.com/33697144/43160812-18407230-8f3b-11e8-99cb-f25bf890da8f.png)
