### ISSUE TITLE
Build UI Skeleton

### ISSUE THREAD

**Issue by bezi** [TheOscars2/FoodApp#3]
#1 has a list of all the screens we sketched up, the first eng goal is to get the project bootstrapped with a simple skeleton.  It should have all the transitions wired up, sans UI elements.  On completion, post a gif/video here and note which commit the video is built on.

**Comment by gtihtina** [comment]
Skeleton for this app MVP is complete. Walkthrough gif attached.

![skeletonwalkthrough](https://user-images.githubusercontent.com/33697144/42850311-d5714420-89db-11e8-9e06-e819eb31f0de.gif)
